noun = input("Type a noun")
adjective = input("type an adjective")
verb = input("type a verb")
adverb = input("type an adverb")
print("I love "+ noun)
print("It keeps me "+ adjective)
print("It helps me "+ verb)
print("I am feeling great "+ adverb)
print("I like it when it "+verb+"me")
print("when it "+verb+"me I "+verb+"")